service: dynatrace-oneagent-sample

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline
  # DYNATRACE: 
  # pull in Dynatrace OneAgent plugin (install first with "npm install --save-dev @dynatrace/serverless-oneagent")
  - "@dynatrace/serverless-oneagent"

package:
  individually: true

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-central-1

functions:
  hello:
    handler: index.hello
    events:
      - http:
          method: GET
          path: hello

  second:
    handler: second.hello
    events:
      - http:
          method: GET
          path: second

custom:
  # DYNATRACE serverless-oneagent plugin configuration.
  serverless-oneagent:
    # npmModuleVersion: string, optional, valid values are: next
    npmModuleVersion: next
    # copy options from serverless configuration screen (Deploy Dynatrace > Setup Serverless integration > Node.js)
    # alternatively, options can be specified on command line with --dt-oneagent-options e.g.
    # $ serverless --dt-oneagent-options='...' package
    options: '{"dynatraceTagPropertyPath":"headers.x-dynatrace","server":"...","tenant":"...","tenanttoken":"..."}'
    # enables extended logging of plugin operations 
    # alternatively, --verbose command line option can be set
    verbose: true
